"""Pipeline status — describes the 6-stage MarketLayer flow.

Aggregates live telemetry from the data lake, strategy lab, signal
engine, and risk gate into a single dashboard-ready response.
"""
from __future__ import annotations

from app.config import get_settings
from app.models.console import (
    PipelineResponse,
    PipelineStage,
    SystemStatus,
)
from app.services import data_lake, risk_gate, signal_engine, strategy_lab


def _data_stage() -> PipelineStage:
    lake = data_lake.status()
    live = sum(1 for s in lake.sources if s.live)
    total = len(lake.sources)
    tone = "ok" if live == total else ("warn" if live > 0 else "danger")
    return PipelineStage(
        id="data",
        order=1,
        label="Data Sources",
        headline=f"{live}/{total} live",
        description=(
            "Prices, filings, and news feeds are available."
        ),
        cta_label="View data sources",
        cta_path="/data-sources",
        metric=", ".join(s.id for s in lake.sources),
        tone=tone,
    )


def _strategy_stage() -> PipelineStage:
    cards = strategy_lab.all_strategies()
    enabled = sum(1 for s in cards if s.enabled)
    return PipelineStage(
        id="strategy",
        order=2,
        label="Strategy Lab",
        headline=f"{enabled} modules enabled",
        description="Strategy modules emit research signals.",
        cta_label="Open Strategy Lab",
        cta_path="/strategy-lab",
        metric=f"{len(cards)} loaded · {enabled} enabled",
        tone="ok" if enabled else "warn",
    )


def _backtest_stage() -> PipelineStage:
    return PipelineStage(
        id="backtest",
        order=3,
        label="Backtest Engine",
        headline="Ready",
        description="Validate signal behavior over historical windows.",
        cta_label="Run backtest",
        cta_path="/backtest-lab",
        metric="real yfinance OHLCV · cached",
        tone="info",
    )


def _signals_stage() -> PipelineStage:
    sigs = signal_engine.all_active_signals(limit_per_ticker=2)
    return PipelineStage(
        id="signals",
        order=4,
        label="Signal Scanner",
        headline=f"{len(sigs)} signals queued",
        description="Active candidates generated by strategy modules.",
        cta_label="Review signals",
        cta_path="/signal-scanner",
        metric=f"{len(sigs)} in review queue",
        tone="ok" if sigs else "muted",
    )


def _risk_stage() -> PipelineStage:
    sigs = signal_engine.top_signals(n=1)
    decision = "passed"
    if sigs:
        decision = risk_gate.run_for_ticker(sigs[0].ticker).decision
    label_map = {
        "passed": ("All checks within thresholds.", "ok"),
        "warning": ("Soft thresholds breached.", "warn"),
        "review_required": ("Review required.", "warn"),
        "blocked": ("Hard check failed.", "danger"),
    }
    text, tone = label_map.get(decision, ("Unknown", "muted"))
    return PipelineStage(
        id="risk",
        order=5,
        label="Risk Gate",
        headline=decision.replace("_", " ").title(),
        description=(
            "Volatility, liquidity, event, data quality, AI confidence, "
            "and simulated portfolio exposure checks."
        ),
        cta_label="Inspect risk",
        cta_path="/risk-gate",
        metric=text,
        tone=tone,
    )


def _ai_stage() -> PipelineStage:
    settings = get_settings()
    provider = settings.ai_provider.lower()
    label_map = {"mock": "Mock provider · safe demo"}
    headline = label_map.get(provider, f"Provider · {provider.upper()}")
    return PipelineStage(
        id="ai_brief",
        order=6,
        label="AI Decision Brief",
        headline=headline,
        description=(
            "Explainable decision-support brief generated after risk "
            "filtering. Research only."
        ),
        cta_label="Open Asset Lab",
        cta_path="/asset-lab",
        metric=f"current provider: {provider}",
        tone="info" if provider == "mock" else "ok",
    )


def status() -> PipelineResponse:
    settings = get_settings()
    return PipelineResponse(
        stages=[
            _data_stage(),
            _strategy_stage(),
            _backtest_stage(),
            _signals_stage(),
            _risk_stage(),
            _ai_stage(),
        ],
        system=SystemStatus(
            ai_provider=settings.ai_provider.lower(),
        ),
    )
